name: Build Project
on:
  push:
    branches:
      - main
jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Launch tests
        run: |
          cd src
          npm i
          npm test

  Build:
    needs:
      - Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create Docker Images and Push
        uses: docker/build-push-action@v4
        with:
          file: docker/prod/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: remirubis/devops-ci-cd:latest