name: Test Project
on:
  push:
    branches:
      - main
jobs:
  DockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Launch tests
        uses: cd src && npm run test
